//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDEdu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aboutu
    {
        public int id { get; set; }
        public string title { get; set; }
        public string desc { get; set; }
        public string icon { get; set; }
        public Nullable<bool> isquestion { get; set; }
        public string image { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
    }
}
