//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDEdu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logo
    {
        public int id { get; set; }
        public string logoImage { get; set; }
        public string logoName { get; set; }
        public string meta { get; set; }
        public string link { get; set; }
        public Nullable<bool> hide { get; set; }
        public string text { get; set; }
        public string desc { get; set; }
        public Nullable<System.DateTime> dateBegin { get; set; }
    }
}
